name: RegionRent
main: com.github.Holyvirus.regionrent.RegionRent
version: 1.0
depend: [WorldGuard, BOSEconomy]
permissions:
    rent.collect:
        description: Allow user to collect rent!
        default: op   
commands:
   rent:
      description: collect your region's rent!
      usage: /rent [collect]
      permission: rent.collect
      permission-message: You don't have don't have permission to use this command!